# Projekt: FLP #1 - plg-2-nka
# Autor:   Daniel Klimaj, xklima22@stud.fit.vutbr.cz
# Datum:   2017-02-27
# Soubor:  Makefile

FILE = plg-2-nka

all:
	ghc --make $(FILE)

clean:
	rm -f $(FILE)
	rm -f $(FILE).o
	rm -f $(FILE).hi

git:
	git add --all
	git commit
	git push -u origin master
