# Projekt: FLP #1 - plg-2-nka
# Autor:   Daniel Klimaj, xklima22@stud.fit.vutbr.cz
# Datum:   2017-02-27
# Soubor:  Makefile

all:
	ghc --make plg2nka

run:
	@./plg2nka

clean:
	rm -f plg2nka
	rm -f plg2nka.o
	rm -f plg2nka.hi
